### ISSUE TITLE
arraybuffer response problem after upload

### ISSUE THREAD

**Issue by fatihpolatli** [leon/angular-upload#33]
hi,

there is a problem when byte array is returned on response after uploading file. i use this for excel files. for a stuation, i upload an excel file and another excel data is returned in response as arraybuffer. bu if you dont set an responseType:"arraybuffer" property on "options" object, it doesnt create a valid excel file. for that, i did a modification;

i added this to params;

<code>isArrayBuffer : '@' // ADDED BY FATIH POLATLI</code>

and added this under options object;
<code>
           // ADDED BY FATIH POLATLI

            if(scope.isArrayBuffer === true || scope.isArrayBuffer === 'true'){

              options.responseType = "arraybuffer";
            }
            //
</code>

you can set it as attribute now and it works;

<code>is-array-buffer="true";</code>

it may be good to add this to project if you want.

thanks

**Comment by leon** [comment]
Arraybuffers are not supported on older browsers, and this plugin needs to work on older browsers.
If you know that you have a newer browser there are simpler ways of getting the job done with FormData.
