### ISSUE TITLE
angular-upload not work IE9

### ISSUE THREAD

**Issue by lombcar** [leon/angular-upload#34]
Here is my html:
 
angular.module('MyApp', ['lr.upload']);

<script src="/mm/js/devel/modules/angular-upload.js"></script>
<body ng-app="MyApp" ng-controller="SummaryController">
<div
						  class="button-file button oro medium"
						  style="width:18%"
						  upload-button
						  data="uploadData"
						  url="/be/documents"
						  on-upload="onFileSelect(files,'carta')"
						  on-success="onFileSuccess(response)"
						>UPLOAD
				   </div>

But not work only with IE9 in console i find this error:
Failed to instantiate module lr.upload due to:
[$injector:nomod] Module 'lr.upload' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.2.25/$injector/nomod?p0=lr.upload
http://errors.angularjs.org/1.2.25/$injector/modulerr?p0=lr.upload&p1=%5B%24injector%3Anomod%5D%20Module%20'lr.upload'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.2.25%2F%24injector%2Fnomod%3Fp0%3Dlr.upload
http://errors.angularjs.org/1.2.25/$injector/modulerr?p0=BffApp&p1=%5B%24injector%3Amodulerr%5D%20F

Can you help me ?
Many thanks

**Comment by leon** [comment]
Double check that you angular-upload is included in your html.
