### ISSUE TITLE
order of form elements in iframe upload preventing uploader working with aws

### ISSUE THREAD

**Issue by fantapop** [leon/angular-upload#36]
Hi,  I'm using your uploader to upload files to S3.  I ran into some problems along the way.  One them them, is that s3 requires the file element to be last in the upload element:

http://docs.aws.amazon.com/AmazonS3/latest/dev/HTTPPOSTForms.html

"The file or content must be the last field in the form. Any fields below it are ignored."

I was able to alleviate this problem by swapping the order that the elements are attached in this code:

```
        angular.forEach(files, function (input) {
          var clone = input.clone(true);
          input.after(clone);
          form.append(input);
        });
        angular.forEach(config.data, function (value, name) {
          var input = angular.element('<input type="hidden" />');
          input.attr('name', name);
          input.val(value);
          form.append(input);
        });
```

I assume there's no other reason, why files would need to be first?  I can submit a pull request for the change.

**Comment by leon** [comment]
That's fine. submit a pull request and I'll merge it

**Comment by leon** [comment]
I'll do a new release shortly

**Comment by fantapop** [comment]
okay, thank you!
